Ensure the TestTask contains the right classes
unbroken-dome/gradle-testsets-plugin pull request #33
Opened 2017-06-19 22:43 UTC by iamdanfox

After upgrading to Gradle 4.0, I found running `./gradlew ete` terminated immediately, with output "No source"!! To debug this, I added:

```gradle
println ete.testClassesDirs.forEach { it -> println it }
```

and saw the following:

```
/Users/dfox/my-repo/some-sub-project/build/classes/java/test
null
```

Not sure why the `map` syntax wasn't working, but I could workaround this by adding:
```
ete.testClassesDirs += sourceSets.ete.output.classesDirs
```

This PR just contributes my fix back to mainline.  I'm no gradle expert, so all feedback/guidance welcome!

2017-06-20 05:39 UTC, tobad357 commented
@iamdanfox can this also be the reason we get NoClassDefFound error for unit tests when running integtests?

2017-06-20 08:31 UTC, tkrullmann commented
Hi @iamdanfox, thanks for the contribution!

The code you changed in `TestTaskListener.groovy` effectively replaces the convention mapping with setting the value directly.

Convention mappings are a somewhat hidden/undocumented feature for custom plugins (unfortunately, because you need to use an internal Gradle class) that allow you to defer evaluation of a task property until after the project is evaluated. This way, the user may override the property or fall back to a - possibly computed - default value otherwise.

If the convention mapping doesn't work as expected, I suspect it may have to do with the value being a collection now (instead of a plain `File` object).

Do you have a sample project to reproduce the issue?

2017-06-20 11:48 UTC, iamdanfox commented
@tobad357, I did get some similar sounding errors, but likewise, I'm not really sure why these unit test classes freak out when I'm running integ tests.

@tkrullmann I'll get a standalone open source project spun up to demonstrate this.  I think this is pretty high priority because people may take the 1.4.0 release expecting it to be compatible with Gradle 4.0 but find all their integTests and etes vacuously pass!!

```
java.lang.ClassNotFoundException: com.palantir.myproject.build.config.BuildOptionsTest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:66)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
```

2017-06-20 13:46 UTC, iamdanfox commented
@tkrullmann, I've got a pretty minimal repro for the gradle 4 problem: 

https://github.com/iamdanfox/gradle-4-testset-repro

This repository has a single unit test and a single integration test, both of which [pass on CI with gradle 3.5][1].  However the [PR][pr] that upgrades to gradle 4 [fails][] on the `integTest` class.  You can see the [junit build report][2] in the artifacts tab.

[1]: https://github.com/iamdanfox/gradle-4-testset-repro/commits/master
[pr]: https://github.com/iamdanfox/gradle-4-testset-repro/pull/1
[fails]: https://circleci.com/gh/iamdanfox/gradle-4-testset-repro/4
[2]: https://4-94894564-gh.circle-artifacts.com/0/home/ubuntu/gradle-4-testset-repro/my-project/build/reports/tests/integTest/index.html

2017-06-20 18:28 UTC, j-baker commented
Can confirm, my integration tests vacuously passed.

2017-06-21 17:10 UTC, dansanduleac approved these changes

2017-06-22 13:03 UTC, tkrullmann commented
I checked the [source code for `JavaPlugin`](https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java#L355) in Gradle 4.0, it's actually setting the `testClassesDir` to the output of the `test` source set, _without_ bothering about a convention mapping:

```java
project.getTasks().withType(Test.class, new Action<Test>() {
    public void execute(final Test test) {
        test.setTestClassesDirs(pluginConvention.getSourceSets().getByName(SourceSet.TEST_SOURCE_SET_NAME).getOutput().getClassesDirs());
        test.getConventionMapping().map("classpath", new Callable<Object>() {
            public Object call() throws Exception {
                return pluginConvention.getSourceSets().getByName(SourceSet.TEST_SOURCE_SET_NAME).getRuntimeClasspath();
            }
        });
    }
});
```

This means we have no chance but set the property directly as well in the `TestTaskListener`.

2017-06-22 13:05 UTC, tkrullmann commented
The `+=` should be replaced by `=` though, otherwise you will get the classes of the `test` source set into every `Test` task (meaning these tests will be run multiple times).

2017-06-22 13:06 UTC, tkrullmann requested changes

2017-06-22 13:06 UTC, tkrullmann commented on src/main/groovy/org/unbrokendome/gradle/plugins/testsets/internal/TestTaskListener.groovy
> +                testTask.testClassesDirs += sourceSet.output.classesDirs
`+=` should be replaced by `=`

2017-06-22 13:48 UTC, iamdanfox commented on src/main/groovy/org/unbrokendome/gradle/plugins/testsets/internal/TestTaskListener.groovy
> +                testTask.testClassesDirs += sourceSet.output.classesDirs
On it. @tkrullmann do you want a comment in there to explain why no convention mapping for gradle 4+?

2017-06-22 14:27 UTC, iamdanfox commented
I published a snapshot locally and tried it out on https://github.com/iamdanfox/gradle-4-testset-repro, looks all happy!

2017-06-22 16:46 UTC, tkrullmann approved these changes

2017-06-22 16:46 UTC, merged

2017-06-22 17:22 UTC, darora commented
@tkrullmann thanks for merging! mind tagging a release with this?

2017-06-22 20:48 UTC, tkrullmann commented
Hi @darora, it should be in version 1.4.1.

2017-06-22 20:52 UTC, tkrullmann commented
Thanks @iamdanfox for the contribution!